version: '3'

services:
  postgres:
    container_name: 'art_db_postgres'
    image: postgres
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
#    ports:
#      - '${POSTGRES_PORT}:5432'

  redis:
    container_name: 'art_db_redis'
    image: redis
    restart: unless-stopped
    env_file:
      - ./.env
    command: redis-server --requirepass ${REDIS_PASSWORD}
#    ports:
#      - '${REDIS_PORT}:6379'

  mongo:
    container_name: 'art_db_mongo'
    image: mongo
    restart: always
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./mongo_data:/data/db
#    ports:
#      - '${MONGO_PORT}:27017'

  api:
    container_name: 'art_service'
    build: .
    image: backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - mongo
      - redis
      - postgres
