# имя Flutter приложения
# обычно данное имя используется в качестве
# названия pub-пакета. Это важно лишь в том случае,
# если вы разрабатываете свой pub-пакет и собираетесь
# выложить его в общий доступ
# как я уже отметил имя Android и iOS приложения впоследствии
# можно будет изменить отдельно для каждой из платформ
name: json_placeholder_app

# краткое описание на английском
description: json_placeholder_app is an demo application

# в данном случае мы не собираемся
# опубликовывать pub-пакет и поэтому
# запрещаем команду flutter publish
publish_to: 'none'

# версия Android и iOS приложения
# состоит из 2 частей, разделенных плюсом
# первая часть - это имя версии, которое будет
# видно для пользователей, например 1.1.5
# вторая часть позволяет Google Play и Apple Store
# отличать разные версии нашего приложения (например: 5)
version: 1.0.0+1

# версия Dart SDK
environment:
  sdk: 3.0.0

# блок зависимостей
dependencies:
  flutter:
    sdk: flutter

  # подключение необходимых pub-пакетов

  # используется для произвольного размещения
  # компонентов в виде сетки
  flutter_staggered_grid_view: ^0.4.0

  # мы будем использовать MVC патте
  mvc_pattern: ^7.0.0

  yandex_mapkit: ^3.2.0
  geolocator: ^9.0.2

  # большая часть данных будет браться из сети,
  # поэтому мы будем использовать http для
  # осуществления наших запросов
  http: ^0.13.3


# зависимости для разработки
# в данном случае подключено тестирование
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.10
  build_runner: ^2.0.4

# в данной секции вы можете подключить шрифты и assets файлы
flutter:

  # указываем, что мы используем MaterialApp иконки и наше
  # приложение соответствует Material Design
  uses-material-design: true


  # указываем кастомные шрифты
  fonts:
    # название семейства шрифтов
    - family: Kalam
      fonts:
        # для каждого файла шрифта мы прописываем
        # соответствующие параметры
        - asset: fonts/Kalam-Regular.ttf
          style: normal
        - asset: fonts/Kalam-Bold.ttf
          weight: 700
          style: normal
        - asset: fonts/Kalam-Light.ttf
          style: normal
          weight: 300

  # прописываем директорию images
  # / указывает на то, что мы собираемся включить
  # все файлы которые будут в директории images
  assets:
    - images/
